// Parity test: the ranker, fed the miniature index and pre-computed query
// vectors that parity-fixture.json carries, must reproduce the fixture's
// ranked scores at f32 precision. No embedder and no staged artifacts, so
// the contract stays inside ordinary CI.
//
// The fixture is a golden generated by nlp/fixtures.ts (regenerate with
// `UPDATE_PARITY_FIXTURE=1`; `tests/nlp/fixtures.test.ts` drift-checks it):
// it pins the ranker's arithmetic against its own past, every op at f32
// precision (`Math.fround` + `Float32Array`).

import { beforeAll, describe, expect, it } from 'vitest';
import { loadRulesYaml } from '../nlp/rules-load';
import { rank } from '../src/lib/ranker/rank';
import type { Rules } from '../src/lib/ranker/rules';
import { loadParityFixture } from './_helpers';

describe('ranker parity', () => {
  let rules: Rules;

  beforeAll(async () => {
    rules = await loadRulesYaml();
  });

  it('reproduces fixture scores at f32 precision', async () => {
    const fixture = await loadParityFixture();
    // A regeneration that emitted nothing would otherwise loop zero times.
    expect(fixture.entries.length).toBeGreaterThan(0);
    expect(fixture.index.records.length).toBeGreaterThan(0);
    for (const entry of fixture.entries) {
      const resolverHit = entry.resolverHit ?? null;
      const ranked = rank(entry.query, entry.queryVec, resolverHit, null, fixture.index, rules);
      // Both sides are f32 values: the ranker computes in f32, the fixture
      // schema frounds on load.
      const got = ranked.slice(0, fixture.limit).map((m) => ({
        category: m.rec.category,
        id: m.rec.id,
        score: m.score
      }));
      expect(got, `query: ${entry.query}`).toEqual(entry.expected);
    }
  });
});
