/** Yodl source files required by the corpus loader. */
export const corpusYodlFiles = [
  "arith.yo",
  "builtins.yo",
  "compsys.yo",
  "compwid.yo",
  "cond.yo",
  "expn.yo",
  "func.yo",
  "grammar.yo",
  "jobs.yo",
  "mod_attr.yo",
  "mod_cap.yo",
  "mod_clone.yo",
  "mod_computil.yo",
  "mod_datetime.yo",
  "mod_db_gdbm.yo",
  "mod_deltochar.yo",
  "mod_langinfo.yo",
  "mod_mapfile.yo",
  "mod_mathfunc.yo",
  "mod_parameter.yo",
  "mod_pcre.yo",
  "mod_private.yo",
  "mod_regex.yo",
  "mod_sched.yo",
  "mod_socket.yo",
  "mod_stat.yo",
  "mod_system.yo",
  "mod_termcap.yo",
  "mod_terminfo.yo",
  "mod_watch.yo",
  "mod_zleparameter.yo",
  "mod_zprof.yo",
  "mod_zpty.yo",
  "mod_zselect.yo",
  "mod_zutil.yo",
  "options.yo",
  "params.yo",
  "prompt.yo",
  "redirect.yo",
  "zle.yo",
] as const

export type CorpusYodlFile = (typeof corpusYodlFiles)[number]
